import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import QueryClient from '@/components/ui/QueryClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <QueryClient>
        <body className='antialiased'>
          <div className='w-screen h-screen p-6 overflow-hidden'>
            <div className='absolute inset-0 bg-grid-paper pointer-events-none z-0 opacity-10'></div>

            <div className='relative bg-[#fffbf4] border-2 border-black rounded-md w-full h-full brand-shadow flex flex-col justify-between !z-10'>
              <Header />
              {children}
              <Footer />
            </div>
          </div>
        </body>
      </QueryClient>
    </html>
  );
}
